# Generated by Django 3.2.19 on 2025-05-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('tags', models.CharField(choices=[('vacation', 'Відпочинок'), ('inspiration', 'Натхнення'), ('life', 'Життя'), ('nature', 'Природа'), ('reading', 'Читання'), ('calm', 'Спокій'), ('harmony', 'Гармонія'), ('music', 'Музика'), ('movies', 'Фільми'), ('travel', 'Подорожі')], max_length=255)),
                ('text', models.TextField()),
                ('article_link', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='media/post_images/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
