# Generated by Django 3.2.19 on 2025-05-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts_app', '0002_alter_user_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.CharField(choices=[('vacation', 'Відпочинок'), ('inspiration', 'Натхнення'), ('life', 'Життя'), ('nature', 'Природа'), ('reading', 'Читання'), ('calm', 'Спокій'), ('harmony', 'Гармонія'), ('music', 'Музика'), ('movies', 'Фільми'), ('travel', 'Подорожі'), ('other', 'Інше')], default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
