# Generated by Django 3.2.19 on 2025-05-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts_app', '0003_auto_20250518_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={},
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.CharField(choices=[('vacation', 'Відпочинок'), ('inspiration', 'Натхнення'), ('life', 'Життя'), ('nature', 'Природа'), ('reading', 'Читання'), ('calm', 'Спокій'), ('harmony', 'Гармонія'), ('music', 'Музика'), ('movies', 'Фільми'), ('travel', 'Подорожі')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='theme',
            field=models.CharField(default='Без теми', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(default='Без назви', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
