# Generated by Django 3.2.19 on 2025-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0004_auto_20250518_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='image9',
        ),
        migrations.AddField(
            model_name='user_post',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.CharField(choices=[('vacation', 'Відпочинок'), ('inspiration', 'Натхнення'), ('life', 'Життя'), ('nature', 'Природа'), ('reading', 'Читання'), ('calm', 'Спокій'), ('harmony', 'Гармонія'), ('music', 'Музика'), ('movies', 'Фільми'), ('travel', 'Подорожі')], default='life', max_length=255),
        ),
    ]
