# Generated by Django 3.2.19 on 2025-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0005_auto_20250518_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={},
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user_post',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AddField(
            model_name='user_post',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AddField(
            model_name='user_post',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AddField(
            model_name='user_post',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.CharField(choices=[('vacation', 'Відпочинок'), ('inspiration', 'Натхнення'), ('life', 'Життя'), ('nature', 'Природа'), ('reading', 'Читання'), ('calm', 'Спокій'), ('harmony', 'Гармонія'), ('music', 'Музика'), ('movies', 'Фільми'), ('travel', 'Подорожі')], max_length=255),
        ),
    ]
