# Generated by Django 5.2.3 on 2025-06-15 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Reg_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 6, 15, 20, 19, 54, 161240, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
