# Generated by Django 5.2.3 on 2025-06-15 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Messenger_App', '0001_initial'),
        ('Posts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='Posts_app.image'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger_App.chatgroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_sent_request', to='Messenger_App.profile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_accepted_request', to='Messenger_App.profile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger_App.profile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='Messenger_App.profile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='Messenger_App.profile'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger_App.profile'),
        ),
    ]
